"""blogmigration

Revision ID: 37e4d2fe47c4
Revises: aad3e8c46a29
Create Date: 2025-06-13 12:39:03.639152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e4d2fe47c4'
down_revision: Union[str, None] = 'aad3e8c46a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
