"""add name

Revision ID: aad3e8c46a29
Revises: 7c23bda94f83
Create Date: 2025-06-13 11:58:58.387172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad3e8c46a29'
down_revision: Union[str, None] = '7c23bda94f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_user', sa.Column('user_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_user', 'user_name')
    # ### end Alembic commands ###
