"""Fix relationships between User, Role, RoleMapping

Revision ID: 0d9492610fc8
Revises: 1d122b468281
Create Date: 2025-06-12 12:32:44.540903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9492610fc8'
down_revision: Union[str, None] = '1d122b468281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
