"""Migration_Changes

Revision ID: 22a0b3090243
Revises: 33cd1f9d0599
Create Date: 2025-06-12 10:45:51.914669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a0b3090243'
down_revision: Union[str, None] = '33cd1f9d0599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rolemaster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rolemaster_id'), 'rolemaster', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rolemaster_id'), table_name='rolemaster')
    op.drop_table('rolemaster')
    # ### end Alembic commands ###
